services:
  database:
    image: mysql:8.0.33
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD:  db_password
    ports:
      - "3306:3306"

  app:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    ports:
      - "8004:8004"

#  mailer:
#    image: axllent/mailpit
#    ports:
#      - "1025"
#      - "8025"
#    environment:
#      MP_SMTP_AUTH_ACCEPT_ANY: 1
#      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  mysql-data:
